'use client';

import React, { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';

export default function TicketsPage() {
  const [tickets, setTickets] = useState<any[]>([]);
  const [filter, setFilter] = useState<string>('all');
  const [loading, setLoading] = useState<boolean>(true);

  const fetchTickets = async () => {
    try {
      const res = await fetch('http://localhost:8085/tickets');
      if (res.ok) {
        const data = await res.json();
        setTickets(data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTickets();
    const interval = setInterval(fetchTickets, 3000);
    return () => clearInterval(interval);
  }, []);

  const filteredTickets = tickets.filter((t) => {
    if (filter === 'all') return true;
    return (
      t.urgency?.toLowerCase() === filter.toLowerCase() ||
      t.status?.toLowerCase() === filter.toLowerCase()
    );
  });

  return (
    <div className="mx-auto w-full max-w-6xl space-y-8 p-6 md:p-8">
      {/* Header */}
      <div className="flex flex-col items-start justify-between gap-4 border-b border-white/10 pb-6 md:flex-row md:items-center">
        <div>
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-rose-500/20 bg-rose-500/10 px-3 py-1 text-[10px] font-bold tracking-wider text-rose-400 uppercase">
            🚨 Human Escalation Dispatch System
          </div>
          <h1 className="text-3xl font-extrabold text-white">Escalated Tickets & Support Queue</h1>
          <p className="mt-1 text-sm text-slate-400">
            Real-time human-help requests generated by Nexus Pay assistant
          </p>
        </div>

        <Button
          onClick={fetchTickets}
          className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-bold text-white transition-all hover:bg-violet-500"
        >
          🔄 Refresh Tickets Queue
        </Button>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2">
        {['all', 'Emergency', 'High', 'Medium', 'Low', 'Pending'].map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`rounded-xl border px-4 py-2 text-xs font-bold capitalize transition-all ${
              filter === f
                ? 'border-violet-500 bg-violet-600 text-white shadow-lg'
                : 'border-white/5 bg-slate-900/50 text-slate-400 hover:text-white'
            }`}
          >
            {f === 'all' ? 'All Escalations' : `${f}`}
          </button>
        ))}
      </div>

      {/* Tickets List */}
      {loading ? (
        <div className="p-12 text-center text-sm text-slate-500">Loading tickets...</div>
      ) : filteredTickets.length === 0 ? (
        <div className="space-y-3 rounded-2xl border border-dashed border-slate-800 p-12 text-center">
          <div className="text-3xl">🎉</div>
          <h3 className="text-base font-bold text-slate-300">No Escalations Found</h3>
          <p className="mx-auto max-w-md text-xs text-slate-500">
            All caller requests have been resolved automatically by Anisha or no human help requests
            match the selected filter.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {filteredTickets.map((ticket) => {
            const urgencyColors: Record<string, string> = {
              Low: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
              Medium: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
              High: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
              Emergency: 'bg-red-500/10 text-red-400 border-red-500/20',
            };
            return (
              <div
                key={ticket.ticket_id}
                className="space-y-4 rounded-2xl border border-white/10 bg-slate-950/70 p-5 shadow-xl backdrop-blur-md transition-all hover:border-violet-500/30"
              >
                <div className="flex items-start justify-between">
                  <div>
                    <span className="block font-mono text-xs font-bold text-violet-400">
                      🎟️ TICKET ID: {ticket.ticket_id}
                    </span>
                    <span className="mt-0.5 block text-[10px] text-slate-500">
                      Created: {ticket.created_at || 'Just now'}
                    </span>
                  </div>
                  <span
                    className={`rounded-full border px-3 py-1 text-[10px] font-bold uppercase ${urgencyColors[ticket.urgency] || 'bg-slate-500/10'}`}
                  >
                    {ticket.urgency} URGENCY
                  </span>
                </div>

                <div className="rounded-xl border border-white/5 bg-slate-900/60 p-3 text-xs leading-relaxed font-medium text-slate-200">
                  "{ticket.summary}"
                </div>

                <div className="grid grid-cols-2 gap-2 border-t border-white/5 pt-2 text-[11px] text-slate-400">
                  <div>
                    <span className="block text-slate-500">Caller Name:</span>
                    <span className="font-bold text-slate-200">
                      {ticket.user_name || 'Anonymous'}
                    </span>
                  </div>
                  <div>
                    <span className="block text-slate-500">Preferred Follow-up:</span>
                    <span className="font-bold text-slate-200">
                      {ticket.followup_method || 'Phone Call'}
                    </span>
                  </div>
                </div>

                <div className="flex items-center justify-between border-t border-white/5 pt-2">
                  <span className="text-[10px] font-extrabold tracking-wider text-emerald-400 uppercase">
                    Status: {ticket.status || 'Pending Review'}
                  </span>
                  <button
                    onClick={() => alert(`Reviewing Ticket #${ticket.ticket_id}`)}
                    className="rounded-lg border border-violet-500/30 bg-violet-600/20 px-3 py-1.5 text-xs font-bold text-violet-300 transition-all hover:bg-violet-600/40"
                  >
                    Assign to Specialist →
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
